codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: '50...100'

    status:
        project:
            default:
                target: auto
        patch: true

component_management:
    default_rules:
        statuses:
            - type: project
              target: 95%
    individual_components:
        - component_id: core
          name: core
          paths:
              - src/app/core/**
        - component_id: shared
          name: shared
          paths:
              - src/app/shared/**
        - component_id: contact
          name: contact
          paths:
              - src/app/views/contact-view/**
        - component_id: edition
          name: edition
          paths:
              - src/app/views/edition-view/**
        - component_id: home
          name: home
          paths:
              - src/app/views/home-view/**
        - component_id: page-not-found
          name: page-not-found
          paths:
              - src/app/views/page-not-found-view/**
        - component_id: statistics
          name: statistics
          paths:
              - src/app/views/statistics-view/**
        - component_id: structure
          name: structure
          paths:
              - src/app/views/structure-view/**

comment:
    layout: 'reach, diff, components, files, footer'
    behavior: default
    require_changes: false
