enableScripts: false

npmMinimalAgeGate: '3d'

approvedGitRepositories:
    ['https://github.com/yarnpkg/*', 'ssh://git@github.com/yarnpkg/*', 'https://github.com/musicenfanthen/rdfstore-js']

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.16.0.cjs
