module.exports = {
    extends: ['@commitlint/config-angular'],
    rules: {
        'scope-case': [2, 'always', ['lower-case', 'upper-case']],
        'scope-empty': [2, 'never'],
        'scope-enum': [
            2,
            'always',
            [
                'app',
                'assets',
                'contact',
                'core',
                'deps',
                'deps-dev',
                'edition',
                'gh-actions',
                'home',
                'page-not-found',
                'search',
                'shared',
                'side-info',
                'structure',
                'testing',
                'views',
                'CHANGELOG',
                'CONTRIBUTING',
                'LICENSE',
                'README',
            ],
        ],
    },
};
