/* eslint-disable @typescript-eslint/naming-convention */

/**
 * Test helper data file: mockResourceContextResponseJson.
 *
 * It provides a mocked ResourceContextResponseJson
 * response from the Salsah API.
 *
 * Exposed to be called from tests.
 */
export const mockResourceContextResponseJson = {
    status: 0,
    userdata: {
        lang: 'en',
    },
    resource_context: {
        res_id: ['2173574', '2173577'],
        resclass_name: 'image',
        preview: [
            {
                path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=thumbnail',
                protocol: 'file',
                origname: 'Programm_Prag19350109_op7-1.jpg',
                format_name: 'JPEG',
                nx: 0,
                ny: 0,
                duration: '0.000',
                fps: '0.000',
            },
            {
                path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=thumbnail',
                protocol: 'file',
                origname: 'Programm_Prag19350109_op7-2.jpg',
                format_name: 'JPEG',
                nx: 0,
                ny: 0,
                duration: '0.000',
                fps: '0.000',
            },
        ],
        locations: [
            [
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=thumbnail',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG',
                    nx: 0,
                    ny: 0,
                    duration: '0.000',
                    fps: '0.000',
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=full&reduce=5',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=full&reduce=4',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=full&reduce=3',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=full&reduce=2',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=full&reduce=1',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173574&qtype=full&reduce=0',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-1.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
            ],
            [
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=thumbnail',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG',
                    nx: 0,
                    ny: 0,
                    duration: '0.000',
                    fps: '0.000',
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=full&reduce=5',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=full&reduce=4',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=full&reduce=3',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=full&reduce=2',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=full&reduce=1',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
                {
                    path: 'https://www.salsah.org/core/sendlocdata.php?res=2173577&qtype=full&reduce=0',
                    protocol: 'file',
                    origname: 'Programm_Prag19350109_op7-2.jpg',
                    format_name: 'JPEG2000',
                    nx: 0,
                    ny: 0,
                    duration: 0,
                    fps: 0,
                },
            ],
        ],
        firstprop: ['Programm_Prag_19350109_Bild_1_2', 'Programm_Prag_19350109_Bild_2_2'],
        region: ['', ''],
        context: 2,
        resinfo: {
            project_id: '6',
            person_id: '32',
            restype_id: '125',
            handle_id: null,
            restype_name: 'webern:supplement',
            restype_label: 'Supplement',
            restype_description: 'Supplement',
            restype_iconsrc:
                'https://www.salsah.org/core/location.php?table=resource_type&field=icon&keyfield=id&keyvalue=125',
            preview: null,
            locations: null,
            locdata: null,
            resclass_name: 'object',
            resclass_has_location: false,
            lastmod: '2017-12-05 15:16:17',
            lastmod_utc: '2017-12-05 14:16:17',
            value_of: 0,
            firstproperty: '[Programm:] Sdru\u017een\u00ed pro soudobou houdbu v Praze',
        },
        canonical_res_id: '2173561',
    },
};
