name: Visualize repo with diagram

on:
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    visualize_repo:
        permissions:
            contents: write # for githubocto/repo-visualizer to commit and push diagrams
        runs-on: ubuntu-latest

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
              with:
                  ref: develop
                  token: ${{ secrets.REPO_TOKEN }}

            - name: Update diagram
              uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
              with:
                  excluded_paths: '.github,.husky,.yarn'
