name: Visualize repo with diagram

on:
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    visualize_repo:
        permissions:
            contents: write # for githubocto/repo-visualizer to commit and push diagrams
        runs-on: ubuntu-latest

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  ref: develop
                  token: ${{ secrets.REPO_TOKEN }}

            - name: Update diagram
              uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
              with:
                  excluded_paths: '.github,.husky,.yarn'
