name: Visualize repo with diagram

on:
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    visualize_repo:
        permissions:
            contents: write # for githubocto/repo-visualizer to commit and push diagrams
        runs-on: ubuntu-latest

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  ref: develop
                  token: ${{ secrets.REPO_TOKEN }}

            - name: Update diagram
              uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # v0.9.1
              with:
                  excluded_paths: '.github,.husky,.yarn'
